### PR TITLE
Create EmailThemeAlphaConfig type

### PR DESCRIPTION
**Pull request by Alixers505**
https://southcomm.atlassian.net/browse/DEV-29

Examples from `ebm_ee`

Direct query of a config:
```graphql
query {
  emailThemeAlphaConfig(input: { id: "5c9d1dde6e705634008b459a" }) {
    id
    status
    accentFontColor
    newsletter {
      id
      name
    }
    # additional fields to return...
  }
}
```
```json
{
  "data": {
    "emailThemeAlphaConfig": {
      "id": "5c9d1dde6e705634008b459a",
      "status": 1,
      "accentFontColor": "#000000",
      "newsletter": {
        "id": "5c9d1dd36e705634008b4598",
        "name": "Evaluation Engineering Weekly Update"
      }
    }
  }
}
```

Accessing configs directly off a newsletter:
```graphql
query {
  emailNewsletter(input: { id: "5c9d1dd36e705634008b4598" }) {
    id
    name
    alphaThemeConfigs {
      edges {
        node {
          id
          status
          accentFontColor
        }
      }
    }
  }
}
```
```json
{
  "data": {
    "emailNewsletter": {
      "id": "5c9d1dd36e705634008b4598",
      "name": "Evaluation Engineering Weekly Update",
      "alphaThemeConfigs": {
        "edges": [
          {
            "node": {
              "id": "5c9d1dde6e705634008b459a",
              "status": 1,
              "accentFontColor": "#000000"
            }
          }
        ]
      }
    }
  }
}
```

### CODE REVIEW

**Review by CaitlynKnudsvig — DISMISSED** [review]

**Comment by CaitlynKnudsvig** [comment]
I don't have permissions to assign a reviewer, but could you take a look at this when you get a sec, @zarathustra323?  We're moving some of `EmailBlock` fields from the legacy platform onto the `Product\Newsletter` model so they can be customized by the user in base (/email-campaigns).  Currently, the user can only customize these fields in the interface for the legacy newsletters, and we want to replicate that functionality for the new framework.

I *think* this is the only place they need to be added within the `base-cms/base-cms` repo, but let us know if something's missing.  Relates to: https://github.com/cygnusb2b/base-platform/pull/4438/files

**Review by zarathustra323 — CHANGES_REQUESTED** [review]
@CaitlynKnudsvig since these fields are related to configuration and, ultimately, independent presentation, I'd prefer to leave them off the newsletter model.

Instead of adding these fields here, can a separate configuration model be used, that has a relationship back to the newsletter (via it's `id`)? For some reason I thought configuration already worked this way in `base-platform` - or am I mistaken?

**Comment by zarathustra323** [comment]
@CaitlynKnudsvig it does appear that configuration is already a model in platform: https://github.com/cygnusb2b/base-platform/blob/master/app/config/platform/models/modelspaces/configuration/email.yml

Can you not re-use this?

**Comment by CaitlynKnudsvig** [comment]
@zarathustra323 Maybe!  I only know how to use what's directly on the product model, but I can try using what's on `Email\ThemeAlpha` instead.  Then we'd just need to move the fields from the `EmailBlock\Header` like headerLeft, headerRight, headerLink, etc. to `Email\ThemeAlpha` instead of  `Product\Newsletter`, right?

**Comment by zarathustra323** [comment]
@CaitlynKnudsvig weren't those fields just now added to the `Product\Newsletter` model? Or were you always storing the values there and just never defined the fields on the model?

Yes, my preference would be to use a core config model, like `Email\ThemeAlpha` since it's already created and likely in use already?

**Comment by CaitlynKnudsvig** [comment]
Yea, the fields that were on `EmailBlock\Header` were just added to `Product\Newsletter` last week in preparation for this, so that will need to be modified in `base-platform` as well.  I'll get started on moving those fields to `Email\ThemeAlpha` instead. 👍

**Comment by zarathustra323** [comment]
Excellent. Thanks much :)

**Comment by CaitlynKnudsvig** [comment]
Just submitted a PR to modify those fields here: https://github.com/cygnusb2b/base-platform/pull/4441/files where I added a couple new fields that we'll need to add to this PR as well- 
```
manageSubscriptions: String @projection
contactUs: String @projection
advertise: String @projection
```

Once that goes live, do we just wrap these fields within something like: `input EmailThemeAlpha {}` ? And/or do they need to be added to another file?

**Comment by zarathustra323** [comment]
Input fields are for modifying how fields are returned. In this case, these fields need to move to a completely different GraphQL type, and then a rel field needs to be added to either the Newsletter to retrieve the config, or a config query needs to be added so you can explicitly query for the configuration model that you want. I can provide you with an example to get you started... can you provide me with an account/group newsletter that currently has a config that I can use for the example?

**Comment by zarathustra323** [comment]
@CaitlynKnudsvig see my latest commit. I added a new GraphQL type called `EmailThemeAlphaConfig` along with some basic queries and also added a related field on newsletters called `EmailNewsletter.alphaThemeConfigs` which returns all configs associated with the given newsletter. _Please use this as a reference for any new GraphQL types you might need to add in the future_ :)

I moved the config fields that were original placed on `EmailNewsletter` to the `EmailThemeAlphaConfig` type, but you may need to add more if some are missing.

Note: technically the way Base is modeled, a newsletter can have more than one config, so you'll need to determine how to deal with that. You an either query a specific _config_ model directly by it's config id via the `emailThemeAlphaConfig` query, or you can return the config via `EmailNewsletter.alphaThemeConfigs` and make sure there is only one in the database.

**Review by zarathustra323 — APPROVED** [review]

**Review by zarathustra323 — APPROVED** [review]

**Pull request merged**
