### PR TITLE
Updated example-newsletters-ien to a working env for ien-today enl template

### PR DESCRIPTION
**Pull request by Alixers505**

### CODE REVIEW

**Comment by Alixers505** [comment]
> Why are all of these templates being added to the repo?

Without that reference, I receive this error:

```

An unexpected error occurred: Network error: Response not successful: Received status code 400Error: Network error: Response not successful: Received status code 400     at new ApolloError (/base-cms/node_modules/apollo-client/bundle.umd.js:92:26)     at /base-cms/node_modules/apollo-client/bundle.umd.js:1587:34     at /base-cms/node_modules/apollo-client/bundle.umd.js:2007:15     at Set.forEach (<anonymous>)     at /base-cms/node_modules/apollo-client/bundle.umd.js:2005:26     at Map.forEach (<anonymous>)     at QueryManager.broadcastQueries (/base-cms/node_modules/apollo-client/bundle.umd.js:2003:20)     at /base-cms/node_modules/apollo-client/bundle.umd.js:1482:29     at process._tickCallback (internal/process/next_tick.js:68:7)[   {     "message": "Variable \"$input\" got invalid value { sectionId: 52258, date: 1591761600000, limit: 1, skip: 0 }; Field newsletterId of required type ObjectID! was not provided.",     "locations": [       {         "line": 1,         "column": 39       }     ],     "extensions": {       "code": "INTERNAL_SERVER_ERROR",       "exception": {         "stacktrace": [           "GraphQLError: Variable \"$input\" got invalid value { sectionId: 52258, date: 1591761600000, limit: 1, skip: 0 }; Field newsletterId of required type ObjectID! was not provided.",           "    at /base-cms/node_modules/graphql/execution/values.js:116:15",           "    at coerceInputValueImpl (/base-cms/node_modules/graphql/utilities/coerceInputValue.js:99:11)",           "    at coerceInputValueImpl (/base-cms/node_modules/graphql/utilities/coerceInputValue.js:54:14)",           "    at coerceInputValue (/base-cms/node_modules/graphql/utilities/coerceInputValue.js:37:10)",           "    at _loop (/base-cms/node_modules/graphql/execution/values.js:109:69)",           "    at coerceVariableValues (/base-cms/node_modules/graphql/execution/values.js:121:16)",           "    at getVariableValues (/base-cms/node_modules/graphql/execution/values.js:48:19)",           "    at buildExecutionContext (/base-cms/node_modules/graphql/execution/execute.js:184:61)",           "    at executeImpl (/base-cms/node_modules/graphql/execution/execute.js:89:20)",           "    at Object.execute (/base-cms/node_modules/graphql/execution/execute.js:64:35)"         ]       }     }   } ]
--



```

**Comment by zarathustra323** [comment]
Are you trying to boot the example newsletter instance for a particular reason?

That error is core there being a section reference that no longer exists in the example (I believe)... the templates themselves do not need to be there to boot the instance. The `TENANT_KEY` change you made in docker compose is all that should be necessary.

**Comment by Alixers505** [comment]
@zarathustra323 - https://www.pivotaltracker.com/story/show/171242971 testing for this

**Comment by zarathustra323** [comment]
You're receiving that error because you likely don't have the `MONGO_DSN_CAPRICA` env var set in your `.env` file. Or, it's set - but set to dev - and you don't have data copied locally.

The example newsletter service depends on the `graphql-server-caprica` service, which requires `MONGO_DSN_CAPRICA` to be set in order to load data from the database for customers in the caprica stack. I'll message you separately with the connection string

**Pull request closed without merging**
